name: static analyse

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup C++ tools
        uses: llvm/llvm-project@main
        with:
          clang-version: 13
          install-dir: /usr/local

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja

      - name: Build project
        run: cmake --build build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup C++ tools
        uses: llvm/llvm-project@main
        with:
          clang-version: 13
          install-dir: /usr/local

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

  static-analyse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup C++ tools
        uses: llvm/llvm-project@main
        with:
          clang-version: 13
          install-dir: /usr/local

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja

      - name: Build project
        run: cmake --build build

      - name: Static analysis with clang-tidy
        run: clang-tidy -p=build/compile_command.json sources/*.cpp includes/*.hpp -- -std=c++17

      - name: Static analysis with scan-build
        run: scan-build cmake --build build

      
    
